---
title: "demonstrate_bias_V11L05_335_C1_HPC"
output: html_document
date: '2022-12-18'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}

library(SpatialExperiment)
library(ggspavis)
library(nnSVG)
library(scran)

#load in spe object
#load(file = "/dcs04/lieber/lcolladotor/spatialHPC_LIBD4035/spatial_hpc/processed-data/02_build_spe/spe_transform.Rdata")

#sort(unique(spe$sample_id)) 4 capture areas for 8 donors

#subset to one sample
#spe_V11L05_335_C1 <- spe[, spe$sample_id == "V11L05-335_C1"]
#saveRDS(spe_V11L05_335_C1, file = "mean_var_project/spe_V11L05_335_C1_HPC.rds")

spe_V11L05_335_C1 <- readRDS(file = "spe_V11L05_335_C1_HPC.rds")

#nnSVG requires logcounts assay name
spe_V11L05_335_C1 <- logNormCounts(spe_V11L05_335_C1)
assayNames(spe_V11L05_335_C1)

#filter out low expressed genes
#for now using filter_genes() to get 2171/36588 genes, manual umi filter gives 13162/36588 genes
spe_V11L05_335_C1 <- filter_genes(spe_V11L05_335_C1)

# set seed for reproducibility
set.seed(123)
#run nnSVG
spe_V11L05_335_C1 <- nnSVG(spe_V11L05_335_C1)

# show results
rowData(spe_V11L05_335_C1)

# Save an object to a file
saveRDS(spe_V11L05_335_C1, file = "spe_V11L05_335_C1_HPC_nnSVG.rds")

```


```{r plotting}

library(SpatialExperiment)
library(here)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(ggrepel)
library(viridis)


spe <- readRDS(file = "mean_var_project/spe_V11L05_335_C1_HPC_nnSVG.rds")

spe_df <- rowData(spe)

df_nnSVG <- 
  as.data.frame(spe_df)

df_effect <- 
  as.data.frame(df_nnSVG) %>% 
  mutate(l = 1 / phi) %>% 
  filter(rank <= 1000)

# variance vs. mean
ggplot(df_effect, 
       aes(x = mean, y = var, color = LR_stat)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  scale_color_gradient(low = "red", high = "blue") +
  labs(x = "mean logcounts", 
       y = "variance", 
       color = "LR statistic") + 
  ggtitle("nnSVG: human HPC") + 
  theme_bw()

# spatial variance vs. mean
ggplot(df_effect, 
       aes(x = mean, y = sigma.sq, color = LR_stat)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  scale_color_gradient(low = "red", high = "blue") +
  labs(x = "mean logcounts", 
       y = "spatial variance (sigma^2)", 
       color = "LR statistic") + 
  ggtitle("nnSVG: human HPC") + 
  ylim(0,1.5) +                      #note that this line of code removes 3 outliers
  theme_bw()

#outlier_index <- rowData(spe)$sigma.sq > 1.5
#indices <- which(outlier_index == TRUE)
#row.names(rowData(spe))[indices]
#"ENSG00000244734" "ENSG00000188536" "ENSG00000206172"

# nonspatial variance vs. mean
ggplot(df_effect, 
       aes(x = mean, y = tau.sq, color = LR_stat)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  scale_color_gradient(low = "red", high = "blue") +
  labs(x = "mean logcounts", 
       y = "nonspatial variance (tau^2)", 
       color = "LR statistic") + 
  ggtitle("nnSVG: human HPC") + 
  theme_bw()

# proportion spatial variance vs. mean
ggplot(df_effect, 
       aes(x = mean, y = prop_sv, color = LR_stat)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  scale_color_gradient(low = "red", high = "blue") +
  labs(x = "mean logcounts", 
       y = "proportion spatial variance", 
       color = "LR statistic") + 
  ggtitle("nnSVG: human HPC") + 
  theme_bw()

```
