---
title: "create_voom_figure"
output: html_document
date: '2023-07-25'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(ggformula)
library(patchwork)

load("mean_var_project/objs_breast.Rdata")

dat <- data.frame(
  y = sqrt(s_g),
  x = r_tilda
) 

p1 <- ggplot(dat, aes(x=x, y=y)) +
  geom_point(size=0.5) +
  ylim(c(0.15, 1)) + xlim(c(-1,6)) + 
  labs(
    x = "average log2(count size)",
    y = "sqrt(std dev)"
  ) +
  theme_bw()

#add trend label

p2 <- ggplot(dat, aes(x=x, y=y)) +
  geom_point(size=0.5, alpha = 0.2) +
  stat_spline(nknots=10, linewidth=1.5, color="purple") +
  ylim(c(0.15, 1)) + xlim(c(-1,6)) + 
  labs(
    x = "average log2(count size)",
    y = "sqrt(std dev)"
  )  +
  annotate("text", x=3.9, y=0.91, label= "gene-wise mean-var trend") +
  theme_bw() 

#add lines?

p3 <- ggplot(dat, aes(x=x, y=y)) +
  stat_spline(nknots=10, linewidth=1.5, color="purple") +
  ylim(c(0.15, 1)) + xlim(c(-1,6)) + 
  labs(
    x = "fitted log2(count size)",
    y = "sqrt(std dev)"
  )  +
  annotate("text", x=3.9, y=0.91, label= "gene-wise mean-var trend") +
  theme_bw() 

pdf("proposal/fig3.pdf", width = 15, height = 4)

wrap_plots(p1, p2, p3, ncol=3, nrow=1)
dev.off()

```

