---
title: "demonstrate_bias_Br2701_LC_round2"
output: html_document
date: '2022-11-29'
---

```{r lc}

library(SpatialExperiment)
library(ggspavis)
library(WeberDivechaLCdata)
library(nnSVG)

#need R 4.2 on jhpce

#download LC data
spe <- WeberDivechaLCdata_Visium()
#subset one sample
spe_Br2701_LC_round2 <- spe[, spe$sample_id == "Br2701_LC_round2"]

#plotSpots(spe_Br2701_LC_round2)

#https://github.com/lmweber/locus-c/blob/main/code/analyses/06_LC_gene_filtering.R
# filter out genes with extremely low expression
# using simple threshold on total UMI counts summed across all spots
n_umis <- 80
ix_low_genes <- rowSums(counts(spe_Br2701_LC_round2)) < n_umis
table(ix_low_genes)

spe_Br2701_LC_round2 <- spe_Br2701_LC_round2[!ix_low_genes, ]
dim(spe_Br2701_LC_round2)

# new zeros may have been created after spot-level QC and filtering low-expressed genes
# no zeros in this table
ix_zero_genes <- rowSums(counts(spe_Br2701_LC_round2)) == 0
table(ix_zero_genes)

# set seed for reproducibility
set.seed(123)
#run nnSVG
spe_Br2701_LC_round2 <- nnSVG(spe_Br2701_LC_round2)

# show results
rowData(spe_Br2701_LC_round2)

# Save an object to a file
saveRDS(spe_Br2701_LC_round2, file = "spe_Br2701_LC_round2_lowexpr_filter_nnSVG.rds")


```

```{r plotting}

library(SpatialExperiment)
library(here)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(ggrepel)
library(viridis)

# Restore the object
res_list <- list(
  humanDLPFC_nnSVG = rowData(readRDS(file = "mean_var_project/spe_Br2701_LC_round2_lowexpr_filter_nnSVG.rds")))

# add method names to all columns except gene IDs and gene names
colnames(res_list[["humanDLPFC_nnSVG"]])[-(1:2)] <- paste0(colnames(res_list[["humanDLPFC_nnSVG"]]), "_nnSVG")[-(1:2)]

df_nnSVG <- 
  as.data.frame(res_list$humanDLPFC_nnSVG)

df_effect <- 
  as.data.frame(df_nnSVG) %>% 
  mutate(l_nnSVG = 1 / phi_nnSVG) %>% 
  filter(rank_nnSVG <= 1000)


# variance vs. mean
ggplot(df_effect, 
       aes(x = mean_nnSVG, y = var_nnSVG, color = LR_stat_nnSVG)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  labs(x = "mean logcounts", 
       y = "variance", 
       color = "LR statistic") + 
  ggtitle("nnSVG: human LC") + 
  theme_bw()

# spatial variance vs. mean
ggplot(df_effect, 
       aes(x = mean_nnSVG, y = sigma.sq_nnSVG, color = LR_stat_nnSVG)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  labs(x = "mean logcounts", 
       y = "spatial variance (sigma^2)", 
       color = "LR statistic") + 
  ggtitle("nnSVG: human LC") + 
  theme_bw()

# nonspatial variance vs. mean
ggplot(df_effect, 
       aes(x = mean_nnSVG, y = tau.sq_nnSVG, color = LR_stat_nnSVG)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  labs(x = "mean logcounts", 
       y = "nonspatial variance (tau^2)", 
       color = "LR statistic") + 
  ggtitle("nnSVG: human LC") + 
  theme_bw()

# proportion spatial variance vs. mean
ggplot(df_effect, 
       aes(x = mean_nnSVG, y = prop_sv_nnSVG, color = LR_stat_nnSVG)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  labs(x = "mean logcounts", 
       y = "proportion spatial variance", 
       color = "LR statistic") + 
  ggtitle("nnSVG: human LC") + 
  theme_bw()

```


```{r plotting2}

library(SpatialExperiment)
library(here)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(ggrepel)
library(viridis)


spe <- readRDS(file = "mean_var_project/spe_Br2701_LC_round2_lowexpr_filter_nnSVG.rds")

# of spots these genes have more than 0 counts/ # of total in-tissue spots -- how to add this to meta data, follow mitochondria example
total_spots <- dim(spe)[2]
sparsity_metric <- rowSums(counts(spe) != 0) / total_spots
rowData(spe)$sparsity_metric <- sparsity_metric

spe_df <- rowData(spe)

df_nnSVG <- 
  as.data.frame(spe_df)

df_effect <- 
  as.data.frame(df_nnSVG) %>% 
  mutate(l = 1 / phi) %>% 
  filter(rank <= 1000)

# variance vs. mean
ggplot(df_effect, 
       aes(x = mean, y = var, color = sparsity_metric)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  labs(x = "mean logcounts", 
       y = "variance", 
       color = "sparsity metric") + 
  ggtitle("nnSVG: human LC") + 
  theme_bw()

# spatial variance vs. mean
ggplot(df_effect, 
       aes(x = mean, y = sigma.sq, color = sparsity_metric)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  labs(x = "mean logcounts", 
       y = "spatial variance (sigma^2)", 
       color = "sparsity metric") + 
  ggtitle("nnSVG: human LC") + 
  theme_bw()

# nonspatial variance vs. mean
ggplot(df_effect, 
       aes(x = mean, y = tau.sq, color = sparsity_metric)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  labs(x = "mean logcounts", 
       y = "nonspatial variance (tau^2)", 
       color = "sparsity metric") + 
  ggtitle("nnSVG: human LC") + 
  theme_bw()

# proportion spatial variance vs. mean
ggplot(df_effect, 
       aes(x = mean, y = prop_sv, color = sparsity_metric)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  labs(x = "mean logcounts", 
       y = "proportion spatial variance", 
       color = "sparsity metric") + 
  ggtitle("nnSVG: human LC") + 
  theme_bw()

```