---
title: "demonstrate_bias_151507_DLPFC"
output: html_document
date: '2022-11-27'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r spatial_LIBD}
library(spatialLIBD)
library(nnSVG)

#https://github.com/LieberInstitute/spatialLIBD
spe <- fetch_data(type = "spe")

vis_clus(
    spe = spe,
    clustervar = "spatialLIBD",
    sampleid = "151507",
    colors = libd_layer_colors,
    ... = " DLPFC Human Brain Layers\nMade with github.com/LieberInstitute/spatialLIBD"
)

spe_151507 <- spe[, spe$sample_id == "151507"]
spe_151507 <- spe_151507[, !is.na(unfactor(colData(spe_151507)$spatialLIBD))]
spe_151507 <- filter_genes(spe_151507) ##https://github.com/lmweber/nnSVG/issues/7 keep getting error that c++ error: dpotrf failed 
# set seed for reproducibility
set.seed(123)
#run nnSVG
spe_151507 <- nnSVG(spe_151507)

# show results
rowData(spe_151507)

# Save an object to a file
saveRDS(spe_151507, file = "spe_151507_DLPFC_nnSVG.rds")


```

```{r plotting}

library(SpatialExperiment)
library(here)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(ggrepel)
library(viridis)

# Restore the object
res_list <- list(
  humanDLPFC_nnSVG = rowData(readRDS(file = "mean_var_project/spe_151507_DLPFC_nnSVG.rds")))

# add method names to all columns except gene IDs and gene names
colnames(res_list[["humanDLPFC_nnSVG"]])[-(1:2)] <- paste0(colnames(res_list[["humanDLPFC_nnSVG"]]), "_nnSVG")[-(1:2)]

df_nnSVG <- 
  as.data.frame(res_list$humanDLPFC_nnSVG)

df_effect <- 
  as.data.frame(df_nnSVG) %>% 
  mutate(l_nnSVG = 1 / phi_nnSVG) %>% 
  filter(rank_nnSVG <= 1000)


# variance vs. mean
ggplot(df_effect, 
       aes(x = mean_nnSVG, y = var_nnSVG, color = LR_stat_nnSVG)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  labs(x = "mean logcounts", 
       y = "variance", 
       color = "LR statistic") + 
  ggtitle("nnSVG: human DLPFC") + 
  theme_bw()

# spatial variance vs. mean
ggplot(df_effect, 
       aes(x = mean_nnSVG, y = sigma.sq_nnSVG, color = LR_stat_nnSVG)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  labs(x = "mean logcounts", 
       y = "spatial variance (sigma^2)", 
       color = "LR statistic") + 
  ggtitle("nnSVG: human DLPFC") + 
  theme_bw()


# nonspatial variance vs. mean
ggplot(df_effect, 
       aes(x = mean_nnSVG, y = tau.sq_nnSVG, color = LR_stat_nnSVG)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  labs(x = "mean logcounts", 
       y = "nonspatial variance (tau^2)", 
       color = "LR statistic") + 
  ggtitle("nnSVG: human DLPFC") + 
  theme_bw()

# proportion spatial variance vs. mean
ggplot(df_effect, 
       aes(x = mean_nnSVG, y = prop_sv_nnSVG, color = LR_stat_nnSVG)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  labs(x = "mean logcounts", 
       y = "proportion spatial variance", 
       color = "LR statistic") + 
  ggtitle("nnSVG: human DLPFC") + 
  theme_bw()

```


