---
title: "demonstrate_bias_V10B01_086_B1_HPC"
output: html_document
date: '2022-12-18'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}

library(SpatialExperiment)
library(ggspavis)
library(nnSVG)
library(scran)

#load in spe object
#load(file = "/dcs04/lieber/lcolladotor/spatialHPC_LIBD4035/spatial_hpc/processed-data/02_build_spe/spe_transform.Rdata")

#sort(unique(spe$sample_id)) 4 capture areas for 8 donors

#subset to one sample
#spe_V10B01_086_B1 <- spe[, spe$sample_id == "V10B01-086_B1"]
#saveRDS(spe_V10B01_086_B1, file = "mean_var_project/spe_V10B01_086_B1_HPC.rds")

spe_V10B01_086_B1 <- readRDS(file = "mean_var_project/spe_V10B01_086_B1_HPC.rds")

#nnSVG requires logcounts assay name
spe_V10B01_086_B1 <- logNormCounts(spe_V10B01_086_B1)
assayNames(spe_V10B01_086_B1)

#filter out low expressed genes
#for now using filter_genes() to get 1853/36588 genes, manual umi filter gives 13162/36588 genes
spe_V10B01_086_B1 <- filter_genes(spe_V10B01_086_B1)

# set seed for reproducibility
set.seed(123)
#run nnSVG
spe_V10B01_086_B1 <- nnSVG(spe_V10B01_086_B1)

# show results
rowData(spe_V10B01_086_B1)

# Save an object to a file
saveRDS(spe_V10B01_086_B1, file = "spe_V10B01_086_B1_HPC_nnSVG.rds")

```

change color for this sample to new color scheme that can be used in figure 1 so yellows are not washed out

```{r plotting}

library(SpatialExperiment)
library(here)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(ggrepel)
library(viridis)


spe <- readRDS(file = "mean_var_project/spe_V10B01_085_A1_HPC_nnSVG.rds")

spe_df <- rowData(spe)

df_nnSVG <- 
  as.data.frame(spe_df)

df_effect <- 
  as.data.frame(df_nnSVG) %>% 
  mutate(l = 1 / phi) %>% 
  filter(rank <= 1000)

# variance vs. mean
ggplot(df_effect, 
       aes(x = mean, y = var, color = LR_stat)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  labs(x = "mean logcounts", 
       y = "variance", 
       color = "LR statistic") + 
  ggtitle("nnSVG: human HPC") + 
  theme_bw()

# spatial variance vs. mean
ggplot(df_effect, 
       aes(x = mean, y = sigma.sq, color = LR_stat)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  labs(x = "mean logcounts", 
       y = "spatial variance (sigma^2)", 
       color = "LR statistic") + 
  ggtitle("nnSVG: human HPC") + 
  theme_bw()

# nonspatial variance vs. mean
ggplot(df_effect, 
       aes(x = mean, y = tau.sq, color = LR_stat)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  labs(x = "mean logcounts", 
       y = "nonspatial variance (tau^2)", 
       color = "LR statistic") + 
  ggtitle("nnSVG: human HPC") + 
  theme_bw()

# proportion spatial variance vs. mean
ggplot(df_effect, 
       aes(x = mean, y = prop_sv, color = LR_stat)) + 
  geom_point(size = 0.75) + 
  scale_color_viridis(trans = "log10") + 
  labs(x = "mean logcounts", 
       y = "proportion spatial variance", 
       color = "LR statistic") + 
  ggtitle("nnSVG: human HPC") + 
  theme_bw()

```
