---
title: "demonstrate_bias_151507_DLPFC_layers"
output: html_document
date: '2023-01-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(spatialLIBD)
library(nnSVG)

#https://github.com/LieberInstitute/spatialLIBD
spe <- fetch_data(type = "spe")
spe_151507 <- spe[, spe$sample_id == "151507"]

#5 spots have NA layer label
#sum(is.na(unfactor(colData(spe_151507)$spatialLIBD))) 

spe_151507 <- spe_151507[, !is.na(unfactor(colData(spe_151507)$spatialLIBD))]

#repeat same process for all layers
layer_list <- c("L1", "L2", "L3", "L4", "L5", "L6", "WM")
n_umis <- 80

for (layer in layer_list) {
  spe_layer <- spe_151507[, colData(spe_151507)$spatialLIBD == layer]

  # filter out genes with extremely low expression
  # using simple threshold on total UMI counts summed across all spots
  ix_low_genes <- rowSums(counts(spe_layer)) < n_umis
  spe_layer <- spe_layer[!ix_low_genes, ]
  
  # set seed for reproducibility
  set.seed(123)
  
  #run nnSVG
  spe_layer <- nnSVG(spe_layer)
  # show results
  rowData(spe_layer)
  
  # Save an object to a file
  file_name <- paste("spe_151507_", layer, "_DLPFC_nnSVG.rds", sep = "")
  saveRDS(spe_layer, file = file_name)
}

```


```{r}

library(SpatialExperiment)
library(here)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(ggrepel)
library(viridis)
library(ggpubr)

layer_list <- c("L1", "L2", "L3", "L4", "L5", "L6", "WM")
plot_list <- list()
i=1

for (layer in layer_list) {
  
  file_name <- paste("mean_var_project/spe_151507_", layer, "_DLPFC_nnSVG.rds", sep = "")
  spe <- readRDS(file = file_name)
  
  spe_df <- rowData(spe)
  
  df_nnSVG <- 
    as.data.frame(spe_df)
  
  df_effect <- 
    as.data.frame(df_nnSVG) %>% 
    mutate(l = 1 / phi) %>% 
    filter(rank <= 1000)
  
  # variance vs. mean
  var <- ggplot(df_effect, 
         aes(x = mean, y = var, color = LR_stat)) + 
    geom_point(size = 2) + 
    scale_color_viridis(trans = "log10") +
    scale_color_gradient(low = "blue", high = "red") +
    labs(x = "mean logcounts", 
         y = "variance", 
         color = "LR statistic") + 
    theme_bw() + 
    theme(legend.position="none", axis.title.x=element_blank(), axis.title.y=element_blank())
  plot_list[[i]] <- var
  i <- i+1
    
  # spatial variance vs. mean
  spat_var <- ggplot(df_effect, 
         aes(x = mean, y = sigma.sq, color = LR_stat)) + 
    geom_point(size = 2) + 
    scale_color_viridis(trans = "log10") + 
    scale_color_gradient(low = "blue", high = "red") +
    labs(x = "mean logcounts", 
         y = "spatial variance (sigma^2)", 
         color = "LR statistic") + 
    theme_bw() + 
    theme(legend.position="none", axis.title.x=element_blank(), axis.title.y=element_blank())
  plot_list[[i]] <- spat_var
  i <- i+1
  
  # nonspatial variance vs. mean
  nonspat_var <- ggplot(df_effect, 
         aes(x = mean, y = tau.sq, color = LR_stat)) + 
    geom_point(size = 2) + 
    scale_color_viridis(trans = "log10") + 
    scale_color_gradient(low = "blue", high = "red") +
    labs(x = "mean logcounts", 
         y = "nonspatial variance (tau^2)", 
         color = "LR statistic") + 
    theme_bw() + 
    theme(legend.position="none", axis.title.x=element_blank(), axis.title.y=element_blank())
  plot_list[[i]] <- nonspat_var
  i <- i+1
  
  # proportion spatial variance vs. mean
  prop <- ggplot(df_effect, 
         aes(x = mean, y = prop_sv, color = LR_stat)) + 
    geom_point(size = 2) + 
    scale_color_viridis(trans = "log10") + 
    scale_color_gradient(low = "blue", high = "red") +
    labs(x = "mean logcounts", 
         y = "proportion spatial variance", 
         color = "LR statistic") + 
    theme_bw() +
    theme(axis.title.x=element_blank(), axis.title.y=element_blank())

  plot_list[[i]] <- prop
  i <- i+1
}

figure <- ggarrange(plotlist = plot_list,
          ncol = 4, nrow = 7)

title_text <- "DLPFC 151507 nnSVG Stratified by Layers"
annotate_figure(figure, 
                #top = text_grob(title_text, color = "black", face = "bold", size = 14)
                top = "Column 1 Title     Column 2 Title    Column 3 Title     Column 4 Title")
```

```{r}

library(SpatialExperiment)
library(here)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(ggrepel)
library(viridis)
library(ggpubr)
library(patchwork)

layer_list <- c("L1", "L2")
plot_list <- list()
i=1

for (layer in layer_list) {
  
  file_name <- paste("mean_var_project/spe_151507_", layer, "_DLPFC_nnSVG.rds", sep = "")
  spe <- readRDS(file = file_name)
  
  spe_df <- rowData(spe)
  
  df_nnSVG <- 
    as.data.frame(spe_df)
  
  df_effect <- 
    as.data.frame(df_nnSVG) %>% 
    mutate(l = 1 / phi) %>% 
    filter(rank <= 1000)
  
  # variance vs. mean
  var <- ggplot(df_effect, 
         aes(x = mean, y = var, color = LR_stat)) + 
    geom_point(size = 2) + 
    scale_color_viridis(trans = "log10") +
    scale_color_gradient(low = "blue", high = "red") +
    labs(x = "mean logcounts", 
         y = "variance", 
         color = "LR statistic") + 
    theme_bw() + 
    theme(legend.position = "bottom", axis.title.x=element_blank(), axis.title.y=element_blank())
  plot_list[[i]] <- var
  i <- i+1
    
  # spatial variance vs. mean
  spat_var <- ggplot(df_effect, 
         aes(x = mean, y = sigma.sq, color = LR_stat)) + 
    geom_point(size = 2) + 
    scale_color_viridis(trans = "log10") + 
    scale_color_gradient(low = "blue", high = "red") +
    labs(x = "mean logcounts", 
         y = "spatial variance (sigma^2)", 
         color = "LR statistic") + 
    theme_bw() + 
    theme(legend.position = "bottom", axis.title.x=element_blank(), axis.title.y=element_blank())
  plot_list[[i]] <- spat_var
  i <- i+1
  
  # nonspatial variance vs. mean
  nonspat_var <- ggplot(df_effect, 
         aes(x = mean, y = tau.sq, color = LR_stat)) + 
    geom_point(size = 2) + 
    scale_color_viridis(trans = "log10") + 
    scale_color_gradient(low = "blue", high = "red") +
    labs(x = "mean logcounts", 
         y = "nonspatial variance (tau^2)", 
         color = "LR statistic") + 
    theme_bw() + 
    theme(legend.position = "bottom", axis.title.x=element_blank(), axis.title.y=element_blank())
  plot_list[[i]] <- nonspat_var
  i <- i+1
  
  # proportion spatial variance vs. mean
  prop <- ggplot(df_effect, 
         aes(x = mean, y = prop_sv, color = LR_stat)) + 
    geom_point(size = 2) + 
    scale_color_viridis(trans = "log10") + 
    scale_color_gradient(low = "blue", high = "red") +
    labs(x = "mean logcounts", 
         y = "proportion spatial variance", 
         color = "LR statistic") + 
    theme_bw() +
    theme(legend.position = "bottom", axis.title.x=element_blank(), axis.title.y=element_blank())

  plot_list[[i]] <- prop
  i <- i+1
}


glob_lab <- "Proportion of Variance Nonspatial Variance Spatial Variance  Variance"

p_lab <- 
  ggplot() + 
  annotate(geom = "text", x = 1, y = 1, label = glob_lab, angle = 90) +
  coord_cartesian(clip = "off")+
  theme_void()

(p_lab | wrap_plots(plot_list,
           nrow = 4, ncol = 2,
           guides = "collect")) +
  plot_layout(widths = c(.1, 1)) +
  plot_annotation(title = "DLPFC 151507 nnSVG Stratified by Layers", 
                  theme = theme(plot.title = element_text(hjust = 0.5)),
                  tag_levels = list(c("","L1","L2"))) & 
  theme(legend.position = 'bottom')

wrap_plots(plot_list,
           nrow = 4, ncol = 2,
           guides = "collect")  + 
  plot_annotation(title = "DLPFC 151507 nnSVG Stratified by Layers", 
                  theme = theme(plot.title = element_text(hjust = 0.5)),
                  tag_levels = list(c("L1","L2"))) & 
  theme(legend.position = 'bottom')  #https://github.com/thomasp85/patchwork/issues/136 

title_text <- "DLPFC 151507 nnSVG Stratified by Layers"
annotate_figure(figure, 
                #top = text_grob(title_text, color = "black", face = "bold", size = 14)
                top = "Column 1 Title     Column 2 Title    Column 3 Title     Column 4 Title")
```

```{r}

library(SpatialExperiment)
library(here)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(ggrepel)
library(viridis)
library(ggpubr)
library(purrr)

df_fxn <- function(layer) {
  
  file_name <- paste("mean_var_project/spe_151507_", layer, "_DLPFC_nnSVG.rds", sep = "")
  spe <- readRDS(file = file_name)
  
  spe_df <- rowData(spe)
  
  df_nnSVG <- 
    as.data.frame(spe_df)
  
  df_effect <- 
    as.data.frame(df_nnSVG) %>% 
    mutate(l = 1 / phi) %>% 
    filter(rank <= 1000)
  
  df_effect$LR_stat_scaled <- df_effect$LR_stat / max(df_effect$LR_stat)

  #add col of layer name
  df_effect$layer_val <- rep(layer,1000)
  return(df_effect)
}

layer_list <- c("L1", "L2", "L3", "L4", "L5", "L6", "WM")
#create dfs of all layers
layer_df <- map(.x=layer_list, .f=~df_fxn(.x))
#convert to df and rbind, will facet on layer column which was added in df_fxn
all_layers_df <- Reduce(rbind,layer_df)

# variance vs. mean
var <- ggplot(all_layers_df, 
       aes(x = mean, y = var, color = LR_stat_scaled)) + 
  geom_point(size = 2) + 
  geom_smooth(method="loess", color="black", size=0.5) +
  facet_grid(layer_val~., switch = "y") +
  scale_color_viridis(trans = "log10") +
  scale_color_gradient(low = "blue", high = "red") +
  labs(x = "mean logcounts", 
       y = "", 
       color = "LR stat scaled by max",
       title = "variance") + 
  theme_bw() + 
  theme(strip.text.y.left = element_text(angle = 0))

# spatial variance vs. mean
spat_var <- ggplot(all_layers_df, 
       aes(x = mean, y = sigma.sq, color = LR_stat_scaled)) + 
  geom_point(size = 2) + 
  facet_grid(layer_val~., switch = "y") +
  scale_color_viridis(trans = "log10") +
  scale_color_gradient(low = "blue", high = "red") +
  labs(x = "mean logcounts", 
       y = "", 
       color = "LR stat scaled by max",
       title = expression(paste("spatial variance ", sigma^{2}))) + 
  theme_bw() + 
  theme(strip.background = element_blank(), strip.text.y = element_blank())

nonspat_var <- ggplot(all_layers_df, 
       aes(x = mean, y = tau.sq, color = LR_stat_scaled)) + 
  geom_point(size = 2) + 
  facet_grid(layer_val~., switch = "y") +
  scale_color_viridis(trans = "log10") +
  scale_color_gradient(low = "blue", high = "red") +
  labs(x = "mean logcounts", 
       y = "", 
       color = "LR stat scaled by max",
       title = expression(paste("nonspatial variance ", tau^{2}))) + 
  theme_bw() + 
  theme(strip.background = element_blank(), strip.text.y = element_blank())

prop <- ggplot(all_layers_df, 
       aes(x = mean, y = prop_sv, color = LR_stat_scaled)) + 
  geom_point(size = 2) + 
  facet_grid(layer_val~., switch = "y") +
  scale_color_viridis(trans = "log10") +
  scale_color_gradient(low = "blue", high = "red") +
  labs(x = "mean logcounts", 
       y = "", 
       color = "LR stat scaled by max",
       title = expression(paste("prop. spatial variance ", sigma^{2}/(sigma^{2}+tau^{2})))) + 
  theme_bw() + 
  theme(strip.background = element_blank(), strip.text.y = element_blank())

library(patchwork)
wrap_plots(var, spat_var, nonspat_var, prop, guides="collect",
           ncol=4, nrow=1)

#code to check if red points are mitochondrial genes
##VARIANCE
for (layer_num in c(1,2,3,7)) {
  indices <- layer_df[[layer_num]]$var > 2.1
  print(layer_df[[layer_num]]$gene_name[indices])
}

for (layer_num in c(4,6)) {
  indices <- layer_df[[layer_num]]$var > 1.5
  print(layer_df[[layer_num]]$gene_name[indices])
}

for (layer_num in c(5)) {
  indices <- layer_df[[layer_num]]$var > 1.25
  print(layer_df[[layer_num]]$gene_name[indices])
}

##SPATIAL VARIANCE
for (layer_num in c(1,3,7)) {
  indices <- layer_df[[layer_num]]$sigma.sq > 2
  print(layer_df[[layer_num]]$gene_name[indices])
}

for (layer_num in c(2,4)) {
  indices <- layer_df[[layer_num]]$sigma.sq > 1
  print(layer_df[[layer_num]]$gene_name[indices])
}

for (layer_num in c(6)) {
  indices <- layer_df[[layer_num]]$sigma.sq > 1.25
  print(layer_df[[layer_num]]$gene_name[indices])
}

indices <- layer_df[[5]]$sigma.sq > 0.5 & layer_df[[5]]$mean > 3
print(layer_df[[5]]$gene_name[indices])
```
