---
title: "example_use_weights"
output: html_document
date: "2023-04-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(spatialLIBD)
library(nnSVG)
library(BiocParallel)

spe <- fetch_data(type = "spe")
spe_151507 <- spe[, spe$sample_id == "151507"]
spe_151507 <- spe_151507[, !is.na(unfactor(colData(spe_151507)$spatialLIBD))]
spe_151507 <- filter_genes(spe_151507)

# Count Matrix, transpose so each row is a spot, and each column is a gene
y <- t(as.matrix(counts(spe_151507)))
n = dim(spe_151507)[2]

w <- readRDS(file = "mean_var_project/DLPFC_151507_BRISC_estimation_spline.rds")

#ix <- seq_len(ncol(y))
ix <- c(1,2,3)
out_brisc <- bplapply(ix, function(i) {
  
  y_i = y[ ,i]
  X = data.frame(intercept = rep(1, n))
  #intercept only model
  raw_fit <- lm(y_i ~ .-1, X)
  print(summary(raw_fit))
  
  w_i <- w[ ,i]
  wtd_X <- w_i*X
  wtd_y_i <- w_i*y_i
  wtd_fit <- lm(wtd_y_i ~ .-1, wtd_X)
  print(summary(wtd_fit))
  
  #alternatively, use weighted least squares by squaring w_i
  wtd_fit_lm_var <- lm(y_i ~ .-1, X, weights = w_i^2)
  print(summary(wtd_fit_lm_var))
  
  #return both fits to compare
}, BPPARAM = MulticoreParam(workers = 1)) #change to 20 on JHPCE


#Note: this can fit all models at once instead of in loop
raw_fit <- lm(y ~ .-1, X) 

```

```{r}
library(nnSVG)
library(spatialLIBD)
library(scran)

spe <- fetch_data(type = "spe")
spe_151507 <- spe[, spe$sample_id == "151507"]
spe_151507 <- spe_151507[, !is.na(unfactor(colData(spe_151507)$spatialLIBD))]
spe_151507 <- filter_genes(spe_151507)
spe_151507 <- logNormCounts(spe_151507)

# set seed for reproducibility
set.seed(123)
no_weight_output <- nnSVG(spe_151507[c(1:10),])

#multiply by weights after log transf.
w <- readRDS(file = "mean_var_project/DLPFC_151507_BRISC_estimation_spline.rds")
# w <- readRDS(file = "~/Desktop/weights.rds") # For Boyi only # TODO (boyiguo1): delete later
# w <- matrix(1, dim(spe_151507)[2], dim(spe_151507)[1])
# w <- matrix(abs(rnorm(4221*1695, mean = 1, sd = 20)) , nrow = 4221)

weighted_counts <- t(w)*logcounts(spe_151507)
assays(spe_151507) <- assays(spe_151507)[1]
assay(spe_151507, "weighted_logcounts") <- weighted_counts # assign a new entry to assays slot, nnSVG will use "logcounts"

# Make sure nnSVG fixed the interceptless model 
stopifnot(
  "Please update your nnSVG to minimumly v1.5.3 to have the correct result" = 
    packageVersion("nnSVG")>='1.5.3'
)

# set seed for reproducibility
#run nnSVG with covariate
LR_calc <- function(i){
  res = tryCatch({
  set.seed(123)
  weight_output_i <- nnSVG(spe_151507[i,], X=matrix(w[,i]), assay_name = "weighted_logcounts")
  rowData(weight_output_i)$LR_stat
}, error=function(e){
  cat("ERROR :",conditionMessage(e), "\n")
  NA
  })
  return(res)
}

LR_list <- lapply(c(1:dim(spe_151507)[1]),LR_calc)

saveRDS(LR_list, file = "spe_151507_DLPFC_weighted_nnSVG.rds")

```

```{r}
#visualizing change in ranks comparing weighted and unweighted

spe <- readRDS(file = "mean_var_project/spe_151507_DLPFC_nnSVG.rds")

#add LR list as another col in spe_151507
LR_list <- readRDS(file = "mean_var_project/spe_151507_DLPFC_weighted_nnSVG.rds")
rowData(spe)$weighted_LR_stat <- unlist(LR_list)

#remove genes with NA in weighted_LR_stat
NA_indices <- is.na(rowData(spe)$weighted_LR_stat)
spe <- spe[!NA_indices,]

#remove genes with < -1 values in weighted_LR_stat 
neg_indices <- rowData(spe)$weighted_LR_stat < -1
spe <- spe[!neg_indices,]

#rerank genes both unweighted and weighted since we removed genes 
rowData(spe)$rank <- NULL
rowData(spe)$un_weighted_rank <- rank(-1 * rowData(spe)$LR_stat)
rowData(spe)$weighted_rank <- rank(-1 * rowData(spe)$weighted_LR_stat)

#new value for change in rank
rowData(spe)$rank_shift <- rowData(spe)$un_weighted_rank - rowData(spe)$weighted_rank

plot(rowData(spe)$mean, rowData(spe)$rank_shift, main = "Rank Changes DLPFC 151507",
     xlab = "mean expression", ylab = "unweighted rank - weighted rank",
     pch = 19, frame = FALSE)

```


```{r}
library(ggplot2)
library(nnSVG)
library(spatialLIBD)
library(scran)

spe <- fetch_data(type = "spe")
spe_151507 <- spe[, spe$sample_id == "151507"]
spe_151507 <- spe_151507[, !is.na(unfactor(colData(spe_151507)$spatialLIBD))]
spe_151507 <- filter_genes(spe_151507)

#offset indices after 972 because 928 and 972 were not included in the LR list
LRs_DLPFC <- readRDS(file = "mean_var_project/spe_151507_DLPFC_weighted_nnSVG.rds")
#hist(LRs_DLPFC, breaks = 100)
negative_LR_indices <- which(LRs_DLPFC < -1)
negative_LR_indices[11:24] <- negative_LR_indices[11:24] + 2

#ix <- 928 and 972 gave c++ errors so could not calculate LRs
ix <- negative_LR_indices[10]
ix_name <- rowData(spe_151507)$gene_name[ix]

df <- as.data.frame(cbind(spatialCoords(spe_151507), expr = logcounts(spe_151507)[ix, ]))

ggplot(df, aes(x = pxl_col_in_fullres, y = pxl_row_in_fullres, 
               color = expr)) + 
  geom_point(size = 0.8) + 
  coord_fixed() + 
  scale_y_reverse() + 
  scale_color_gradient(low = "gray90", high = "blue", 
                       trans = "sqrt", breaks = range(df$expr), 
                       name = "logcounts") + 
  ggtitle(ix_name) + 
  theme_bw() + 
  theme(plot.title = element_text(face = "italic"), 
        panel.grid = element_blank(), 
        axis.title = element_blank(), 
        axis.text = element_blank(), 
        axis.ticks = element_blank())

```

```{r}
#check if subsetting to reasonable weight values fixes c++ error for DLPFC genes
library(nnSVG)
library(spatialLIBD)
library(scran)

spe <- fetch_data(type = "spe")
spe_151507 <- spe[, spe$sample_id == "151507"]
spe_151507 <- spe_151507[, !is.na(unfactor(colData(spe_151507)$spatialLIBD))]
spe_151507 <- filter_genes(spe_151507)
spe_151507 <- logNormCounts(spe_151507)

#multiply by weights after log transf.
w <- readRDS(file = "mean_var_project/DLPFC_151507_BRISC_estimation_spline.rds")

weighted_counts <- t(w)*logcounts(spe_151507)
assays(spe_151507) <- assays(spe_151507)[1]
assay(spe_151507, "weighted_logcounts") <- weighted_counts # assign a new entry to assays slot, nnSVG will use "logcounts"

# Make sure nnSVG fixed the interceptless model 
stopifnot(
  "Please update your nnSVG to minimumly v1.5.3 to have the correct result" = 
    packageVersion("nnSVG")>='1.5.3'
)

#total 4221 obs
sum(matrix(w[,928]) > 1000) #58 obs out of range
include_indices <- which(matrix(w[,928]) < 1000)

weight_output_i <- nnSVG(spe_151507[928,include_indices], X=matrix(w[include_indices,928]), assay_name = "weighted_logcounts")

max(apply(t(w), 1, max, na.rm=TRUE))
hist(log(apply(t(w), 1, max, na.rm=TRUE)), breaks=50)
```

