
```{r}
#visualizing change in ranks comparing weighted and unweighted

library(SpatialExperiment)
library(here)
library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(ggrepel)
library(viridis)
library(ggpubr)
library(purrr)

spe <- readRDS(file = "mean_var_project/spe_151507_DLPFC_nnSVG.rds")

weighted_output <- readRDS(file = "mean_var_project/spe_151507_DLPFC_weighted_nnSVG.rds")

#add LR list as another col in spe_151507
LR_list <- unlist(lapply(weighted_output, function (x) x[c('weighted_LR_stat')]))
rowData(spe)$weighted_LR_stat <- unlist(LR_list)

#remove genes with NA in weighted_LR_stat
NA_indices <- is.na(rowData(spe)$weighted_LR_stat)
spe <- spe[!NA_indices,]

#remove genes with < -1 values in weighted_LR_stat 
neg_indices <- rowData(spe)$weighted_LR_stat < -1
spe <- spe[!neg_indices,]

#rerank genes both unweighted and weighted since we removed genes 
rowData(spe)$un_weighted_rank <- rank(-1 * rowData(spe)$LR_stat)
rowData(spe)$weighted_rank <- rank(-1 * rowData(spe)$weighted_LR_stat)

#new value for change in rank
rowData(spe)$rank_shift <- rowData(spe)$un_weighted_rank - rowData(spe)$weighted_rank

#plot shift in rank against mean expression 
plot(rowData(spe)$mean, rowData(spe)$rank_shift, main = "Rank Changes DLPFC 151507",
     xlab = "mean expression", ylab = "unweighted rank - weighted rank",
     pch = 20, frame = FALSE)

df <- data.frame(LR_stat = unlist(lapply(weighted_output, function (x) x[c('weighted_LR_stat')])),
                mean = unlist(lapply(weighted_output, function (x) x[c('weighted_mean')])),
                var = unlist(lapply(weighted_output, function (x) x[c('weighted_var')])),
                sigma.sq = unlist(lapply(weighted_output, function (x) x[c('weighted_sigma.sq')])),
                tau.sq = unlist(lapply(weighted_output, function (x) x[c('weighted_tau.sq')])),
                prop_sv = unlist(lapply(weighted_output, function (x) x[c('weighted_prop_sv')])),
                phi = unlist(lapply(weighted_output, function (x) x[c('weighted_phi')])))

region <- "DLPFC"

df <- subset(df, mean < 5e+12) #removes 1 outlier and 2 NA

# variance vs. mean
var <- ggplot(df, 
       aes(x = mean, y = var, color = LR_stat)) + 
  scale_x_continuous(trans = "log10") + 
  scale_y_continuous(trans = "log10") + 
  geom_point(size = 2) + 
  geom_smooth(method="loess", color="black", size=0.5) +
  scale_color_viridis(trans = "log10") +
  scale_color_gradient(low = "blue", high = "red") +
  labs(x = "mean logcounts", 
       y = "variance", 
       color = "LR stat",
       title = region) + 
  theme_bw() + 
  theme(strip.text.y.left = element_text(angle = 0))

# spatial variance vs. mean
spat_var <- ggplot(df, 
       aes(x = mean, y = sigma.sq, color = LR_stat)) + 
  scale_x_continuous(trans = "log10") + 
  scale_y_continuous(trans = "log10") + 
  geom_point(size = 2) + 
  scale_color_viridis(trans = "log10") +
  scale_color_gradient(low = "blue", high = "red") +
  labs(x = "mean logcounts", 
       y = expression(paste("spatial variance ", sigma^{2})), 
       color = "LR stat",
       title = region) + 
  theme_bw() + 
  theme(strip.background = element_blank(), strip.text.y = element_blank())

nonspat_var <- ggplot(df, 
       aes(x = mean, y = tau.sq, color = LR_stat)) + 
  scale_x_continuous(trans = "log10") + 
  scale_y_continuous(trans = "log10") + 
  geom_point(size = 2) + 
  scale_color_viridis(trans = "log10") +
  scale_color_gradient(low = "blue", high = "red") +
  labs(x = "mean logcounts", 
       y = expression(paste("nonspatial variance ", tau^{2})), 
       color = "LR stat",
       title = region) + 
  theme_bw() + 
  theme(strip.background = element_blank(), strip.text.y = element_blank())

prop <- ggplot(df, 
       aes(x = mean, y = prop_sv, color = LR_stat)) + 
  scale_x_continuous(trans = "log10") + 
  geom_point(size = 2) + 
  scale_color_viridis(trans = "log10") +
  scale_color_gradient(low = "blue", high = "red") +
  labs(x = "mean logcounts", 
       y = expression(paste("prop. spatial variance ", sigma^{2}/(sigma^{2}+tau^{2}))), 
       color = "LR stat",
       title = region) + 
  theme_bw() + 
  theme(strip.background = element_blank(), strip.text.y = element_blank())

library(patchwork)
wrap_plots(var, spat_var, nonspat_var, prop, guides="collect",
           ncol=4, nrow=1)

```

```{r}
library(ggplot2)
library(SpatialExperiment)
library(patchwork)
### EXPLORING CHANGING RANKS
#prop sv, sigma.sq, LR pre weighting, LR post weighting, etc.

load(file = "mean_var_project/spe_151507_DLPFC_weighted_nnSVG.rds")
load(file = "mean_var_project/spe_151507_DLPFC_constrained_weighted_nnSVG.rds")

weighted_rank <- rank(-1*rowData(spe_weighted)$weighted_LR_stat)
constrained_weighted_rank <- rank(-1*rowData(spe_constrained_weighted)$weighted_LR_stat)

#new value for change in rank
rank_shift <- rowData(spe_unweighted)$rank - weighted_rank

#plot shift in rank against mean expression 
rank1 <- data.frame(x = rowData(spe_unweighted)$mean,
           y = rank_shift
) |>
  ggplot() +
  geom_point(aes(x = x, y = y), size=0.5) +
  ylim(c(-1600,1600)) +
  labs(title = "Rank Changes simulation: unweighted vs weighted",
       x = "mean expression",
       y = "unweighted rank - weighted rank")

#new value for change in rank
constrained_rank_shift <- rowData(spe_unweighted)$rank - constrained_weighted_rank

#plot shift in rank against mean expression 
rank2 <- data.frame(x = rowData(spe_unweighted)$mean,
           y = constrained_rank_shift
) |>
  ggplot() +
  geom_point(aes(x = x, y = y), size = 0.5) +
  ylim(c(-1600,1600)) +
  labs(title = "Rank Changes simulation: unweighted vs constrained weighted",
       x = "mean expression",
       y = "unweighted rank - constrained weighted rank")

wrap_plots(rank1, rank2, guides = "collect", nrow = 1)

#check if genes with spatial variation ranked higher compared to genes without spatial variation
rank_unw <- data.frame(
  y = rowData(spe_unweighted)$rank,
  x = rowData(spe_unweighted)$mean
) |> 
  ggplot() +
  geom_point(aes(x = x, y = y)) +
  labs(
    x = "mean of logcounts",
    y = "rank",
    title = "unweighted nnSVG"
  )

rank_w <- data.frame(
  y = weighted_rank,
  x = rowData(spe_weighted)$weighted_mean
) |> 
  ggplot() +
  xlim(0,150) +
  geom_point(aes(x = x, y = y)) +
  labs(
    x = "mean of logcounts",
    y = "rank",
    title = "weighted nnSVG"
  )

wrap_plots(rank_unw, rank_w, 
           guides = "collect",
           nrow=1)

rank_cw <- data.frame(
  y = constrained_weighted_rank,
  x = rowData(spe_constrained_weighted)$weighted_mean
) |> 
  ggplot() +
  geom_point(aes(x = x, y = y)) +
  labs(
    x = "mean of logcounts",
    y = "rank",
    title = "constrained weighted nnSVG"
  )

wrap_plots(rank_unw, rank_w, rank_cw,
           guides = "collect",
           nrow=1)

sigma_unw <- data.frame(
  y = rowData(spe_unweighted)$sigma.sq,
  x = rowData(spe_unweighted)$mean
) |> 
  ggplot() +
  geom_point(aes(x = x, y = y)) +
  labs(
    x = "mean of logcounts",
    y = "est sigma.sq",
    title = "unweighted nnSVG"
  )

sigma_w <- data.frame(
  y = rowData(spe_weighted)$weighted_sigma.sq,
  x =  rowData(spe_weighted)$weighted_mean
) |> 
  ggplot() +
  geom_point(aes(x = x, y = y)) +
  #scale_y_continuous(trans='log10') +
  #scale_x_continuous(trans='log10') +
  labs(
    x = "mean of logcounts",
    y = "est sigma.sq",
    title = "weighted nnSVG"
  )


sigma_cw <- data.frame(
  y = rowData(spe_constrained_weighted)$weighted_sigma.sq,
  x =  rowData(spe_constrained_weighted)$weighted_mean
) |> 
  ggplot() +
  geom_point(aes(x = x, y = y)) +
  #scale_y_continuous(trans='log10') +
  #scale_x_continuous(trans='log10') +
  labs(
    x = "mean of logcounts",
    y = "est sigma.sq",
    title = "constrained weighted nnSVG"
  )

wrap_plots(sigma_unw, sigma_w, sigma_cw, guides = "collect", nrow = 1)
```
